services:
  # =====================================
  # USER SERVICE (NestJS + Prisma)
  # =====================================
  user-postgres:
    image: postgres:15-alpine
    container_name: user-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USERDB_USERNAME}
      POSTGRES_PASSWORD: ${USERDB_PASSWORD}
      POSTGRES_DB: ${USERDB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./services/user-service
    container_name: user-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      JWT_PRIVATE_KEY_PATH: /app/private.pem
      JWT_PUBLIC_KEY_PATH: /app/public.pem
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
    volumes:
      - ./services/user-service/private.pem:/app/private.pem:ro
      - ./services/shared/public.pem:/app/public.pem:ro
    depends_on:
      user-postgres:
        condition: service_healthy

  # =====================================
  # TRIP SERVICE (Spring Boot)
  # =====================================
  trip-postgres:
    image: postgres:15-alpine
    container_name: trip-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${TRIPDB_USERNAME}
      POSTGRES_PASSWORD: ${TRIPDB_PASSWORD}
      POSTGRES_DB: ${TRIPDB_DATABASE}
    ports:
      - "5434:5432"
    volumes:
      - trip_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TRIPDB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  trip-service:
    build: ./services/trip_service
    container_name: trip-service
    restart: unless-stopped
    depends_on:
      trip-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${TRIPDB_URL}
      SPRING_DATASOURCE_USERNAME: ${TRIPDB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${TRIPDB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8081:8081"

  # =====================================
  # DRIVER SERVICE (Spring Boot + Redis)
  # =====================================
  driver-redis:
    image: redis:7-alpine
    container_name: driver-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  driver-service:
    build: ./services/driver-service
    container_name: driver-service
    restart: unless-stopped
    depends_on:
      driver-redis:
        condition: service_healthy
    environment:
      REDIS_HOST: driver-redis
      REDIS_PORT: 6379
      JWT_PUBLIC_KEY_PATH: /app/keys/public.pem
    ports:
      - "8082:8082"
      - "5005:5005"
    volumes:
      - ./services/shared/public.pem:/app/keys/public.pem:ro

  # # =====================================
  # # NOTIFICATION SERVICE (NestJS + RabbitMQ)
  # # =====================================
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  #   healthcheck:
  #     test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      JWT_PUBLIC_KEY_PATH: /app/public.pem
    volumes:
      - ./services/shared/public.pem:/app/public.pem:ro
    depends_on:
      rabbitmq:
        condition: service_healthy

  # =====================================
  # KONG API GATEWAY (DB-less)
  # =====================================
  kong:
    image: kong:3.6
    container_name: kong
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
    ports:
      - "8000:8000" # Public requests (Gateway)
      - "8003:8003" # Admin API
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    depends_on:
      user-service:
        condition: service_started
      trip-service:
        condition: service_started
      driver-service:
        condition: service_started
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5


# =====================================
# LOCALSTACK SERVICE
# ===================================== 

  localstack:
      image: localstack/localstack:latest
      ports:
        - "4566:4566"
        - "4571:4571"
      environment:
        - SERVICES=ec2,s3,iam,sts,lambda
        - DEBUG=1
      volumes:
        - "./localstack-data:/var/lib/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"

# =====================================
# VOLUMES
# =====================================
volumes:
  user_postgres_data:
  trip_postgres_data:
  rabbitmq_data:
 