global:
  scrape_interval: 15s #

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Node Exporter
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # cAdvisor
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Redis
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # RabbitMQ
  - job_name: "rabbitmq-exporter"
    static_configs:
      - targets: ["rabbitmq-exporter:9419"]

  # Postgres User DB
  - job_name: "postgres-user"
    static_configs:
      - targets: ["postgres-exporter-user:9187"]

  # Postgres Trip DB
  - job_name: "postgres-trip"
    static_configs:
      - targets: ["postgres-exporter-trip:9187"] # Note: Internal port is 9187, externally mapped to 9188

